import type { NextPage, GetServerSideProps } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { wrapper } from "../app/store";
import { selectProfile, setProfileDate } from "../app/store/slice/profile";
import { useSelector } from "react-redux";

const Home: NextPage = (props: any) => {
	const { resolvedUrl } = props;
	const profile = useSelector(selectProfile);
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to <a href='https://nextjs.org'>Next.js!</a>
					{resolvedUrl}
				</h1>
				<h3>This is redux data :{profile.name}</h3>
				<p>{resolvedUrl}</p>
			</main>
		</div>
	);
};

export const getServerSideProps: GetServerSideProps =
	wrapper.getServerSideProps((store) => async ({ resolvedUrl }) => {
		console.log("resolvedUrl>>", resolvedUrl);
		store.dispatch(setProfileDate("My server name"));
		return {
			props: {
				resolvedUrl,
			},
		};
	});
export default Home;
