import type { NextPage } from "next";
import Link from "next/link";
import Head from "next/head";
const about: NextPage = () => {
	return (
		<div>
			<Head>
				<title>About Page</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Link href='/' passHref>
				<a>Home Page</a>
			</Link>
		</div>
	);
};

export default about;
