import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Images</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<h1>Images</h1>
			<div style={{ width: 500, height: 300, position: "relative" }}>
				<Image
					src='https://images.unsplash.com/photo-1605460375648-278bcbd579a6'
					layout='fill'
					// objectFit='cover'
					alt='A beautiful English Setter'
				></Image>
			</div>
		</div>
	);
};

export default Home;
