import type { NextPage, GetServerSideProps } from "next";
import Head from "next/head";
import { useEffect } from "react";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import axios from "axios";

interface Props {
	users: [User];
}
interface User {
	id: string;
	title: string;
}

export const getServerSideProps: GetServerSideProps = async (context) => {
	const usersReq = await axios.get(
		"https://jsonplaceholder.typicode.com/posts"
	);
	return {
		props: {
			users: usersReq.data,
		},
	};
};

const Home: NextPage<Props> = ({ users }) => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<h1>SSR Rest API</h1>
			<ul>
				{users.map((user: User) => (
					<div className={styles.grid}>
						<Link
							key={user.id}
							href={`/users/${user.id}`}
							className={styles.card}
						>
							<ul>
								<li>
									<h3> {user.title} &rarr;</h3>
								</li>
							</ul>
						</Link>
					</div>
				))}
			</ul>
		</div>
	);
};

export default Home;
