import Head from "next/head";
import { useSelector } from "react-redux";
import Decrement from "../components/Decrement";
import Increment from "../components/increment";
import styles from "../styles/Home.module.css";

export default function Home() {
	//we are in provider of redux so it knows which state we are talking about
	const count = useSelector((state) => state.counter.value); //counter is coming from store reducer
	return (
		<div className={styles.container}>
			<Head>
				<title>Redux Tool Kit</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<h1>The State Counter : {count}</h1>
			<Increment />
			<Decrement />
		</div>
	);
}
