import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Button from "../component/Button";
import FancyButton from "../component/fancyButton";
import HighLight from "../component/HighLight";
import HighLightGlobal from "../component/GlobalText";

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Button name='Styled'></Button>
			<FancyButton name='Styles2'></FancyButton>
			<HighLight text='This is mishaal'></HighLight>
			<HighLightGlobal text='This is mishaal'></HighLightGlobal>
		</div>
	);
};

export default Home;
