import Head from "next/head";
import styles from "../styles/Home.module.css";
import { VStack, Button, Heading } from "@chakra-ui/react";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<VStack padding='10'>
				<Heading>Using Chakra UI For Styling</Heading>
				<Button backgroundColor='brand.100'> brand.100</Button>
				<Button backgroundColor='brand.200'> brand.200</Button>
				<Button backgroundColor='brand.300'> brand.300</Button>
				<Button backgroundColor='brand.400'> brand.400</Button>
			</VStack>
		</div>
	);
}
